from __future__ import annotations

from src.agents.base import AgentContext, BaseAgent
from src.common.models import (
    ArchitecturePlan,
    CodeArtifact,
    DeveloperResult,
    DevelopmentTask,
    FeatureRequest,
)
from src.llm.provider import GenerationRequest


class DeveloperAgent(BaseAgent):
    def __init__(self, name: str, context: AgentContext) -> None:
        super().__init__(name=name, context=context)

    def implement_task(
        self,
        feature: FeatureRequest,
        plan: ArchitecturePlan,
        task: DevelopmentTask,
    ) -> DeveloperResult:
        system_prompt = (
            "You are a senior developer agent. Implement exactly one task and return "
            "concise production-ready code."
        )

        refined_prompt = self._refine_prompt(plan=plan, task=task)

        user_prompt = (
            f"Feature: {feature.title}\n"
            f"Task: {task.title}\n"
            f"Task description: {task.description}\n"
            f"Acceptance criteria: {', '.join(task.acceptance_criteria)}\n"
            f"Refined instructions: {refined_prompt}"
        )
        model_answer = self.context.provider.generate(
            GenerationRequest(system_prompt=system_prompt, user_prompt=user_prompt)
        )

        file_stub = task.title.lower().replace(" ", "_")
        artifact = CodeArtifact(
            task_id=task.task_id,
            language="python",
            file_path=f"generated/{file_stub}.py",
            code=(
                "\n".join(
                    [
                        f"# Generated by {self.name} for task {task.task_id}",
                        f"# Refined prompt: {refined_prompt}",
                        "def execute():",
                        f"    return {model_answer!r}",
                    ]
                )
                + "\n"
            ),
            notes=["Replace placeholder function with concrete project code."],
        )

        return DeveloperResult(
            task_id=task.task_id,
            agent_name=self.name,
            rationale=(
                "Implemented task from architect global prompt and task seed with "
                "developer-level refinement."
            ),
            artifacts=[artifact],
        )

    @staticmethod
    def _refine_prompt(plan: ArchitecturePlan, task: DevelopmentTask) -> str:
        return " | ".join(
            [
                plan.global_prompt,
                task.developer_prompt_seed,
                "Follow project coding standards and preserve readability.",
            ]
        )
